export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE'
export const SELECT_ONE_PRODUCT = 'SELECT_ONE_PRODUCT'
export const DELETE_DATA = "DELETE_DATA"
